name: Build Example PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: example.tex
        latexmk_use_xelatex: false
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: example-pdf
        path: example.pdf
        
    - name: Release PDF (on tag push)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: example.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
